import { themes } from "prism-react-renderer";

export const languages = [
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "cpp", label: "C++" },
  { value: "typescript", label: "TypeScript" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "kotlin", label: "Kotlin" },
  { value: "scala", label: "Scala" },
  { value: "dart", label: "Dart" },
  { value: "r", label: "R" },
  { value: "shell", label: "Shell" },
  { value: "powershell", label: "PowerShell" },
  { value: "sql", label: "SQL" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "markdown", label: "Markdown" },
  { value: "yaml", label: "YAML" },
  { value: "json", label: "JSON" },
  { value: "xml", label: "XML" },
  { value: "graphql", label: "GraphQL" },
  { value: "lua", label: "Lua" },
  { value: "perl", label: "Perl" },
  { value: "haskell", label: "Haskell" },
  { value: "matlab", label: "MATLAB" },
  { value: "objectivec", label: "Objective-C" },
] as const;

export const codeThemes = {
  nightOwl: themes.nightOwl,
  dracula: themes.dracula,
  vsLight: themes.vsLight,
  github: themes.github,
  vsDark: themes.vsDark,
} as const;

export const gradients = {
  sunset: "bg-gradient-to-r from-orange-500 via-red-500 to-pink-500",
  ocean: "bg-gradient-to-r from-blue-400 via-teal-500 to-emerald-500",
  forest: "bg-gradient-to-r from-green-400 via-lime-500 to-emerald-600",
  lavender: "bg-gradient-to-r from-indigo-300 via-purple-400 to-pink-400",
  midnight: "bg-gradient-to-r from-blue-900 via-indigo-900 to-purple-900",
  aurora: "bg-gradient-to-r from-purple-500 via-pink-500 to-orange-500",
  desert: "bg-gradient-to-r from-yellow-600 via-orange-600 to-red-600",
  mountain: "bg-gradient-to-l from-green-600 via-blue-600 to-indigo-600",
  city: "bg-gradient-to-r from-gray-600 via-blue-600 to-purple-600",
  beach: "bg-gradient-to-r from-blue-600 via-green-600 to-yellow-600",
  dawn: "bg-gradient-to-r from-pink-600 via-yellow-600 to-green-600",
  dusk: "bg-gradient-to-r from-purple-600 via-pink-600 to-red-600",
  rainforest: "bg-gradient-to-r from-green-600 via-blue-600 to-purple-600",
  glacier: "bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600",
  volcano: "bg-gradient-to-r from-red-600 via-orange-600 to-yellow-600",
} as const;
